### PR TITLE
Merge from develop

### PR DESCRIPTION
**Pull request by hotungkhanh**
- Changed CI/CD pipeline to only run on pushes to `main`
- Added new sections to README

### CODE REVIEW

**Review by JackTong24 — COMMENTED** [review]
I wonder if it will be more complete to mention Timefold API in the tech stack section.
Besides, do we need to put the login details for client into README.md file?

**Comment by hotungkhanh** [comment]
> I wonder if it will be more complete to mention Timefold API in the tech stack section. Besides, do we need to put the login details for client into README.md file?

We will keep updating the README file, so we can add Timefold at a later commit.
Since the repository is public, we cannot put login details, which needs to be secret, onto the file.

**Review by NguyenDonLam — APPROVED** [review]

**Review by JackTong24 — APPROVED** [review]
Tested. The README file may need futher adjustment later.

**Review by dh-giang-vu — APPROVED** [review]
Great job team 🙌

**Review by FlyingPufferFish — APPROVED** [review]
Look good, nice work 🎉

**Pull request merged**
